version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/reading_progress
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=StrongPassword123

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=reading_progress
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=StrongPassword123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 